CREATE TABLE IF NOT EXISTS quick_launch_configurations (
  version INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  status TEXT NOT NULL,
  draft JSONB NOT NULL,
  published JSONB,
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ(6) NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS quick_launch_configurations_status_version_idx
  ON quick_launch_configurations(status, version);
