import { useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, Button, FlatList, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useLocalSearchParams } from 'expo-router';
import { MobileApiClient } from '../src/api-client';
import { MobileMessagingService, type MobileMessage, type MobileNotification } from '../src/messaging-service';
import { MobileSession } from '../src/session';
import { secureCredentialStore } from '../src/secure-credential-store';
const baseUrl=process.env.EXPO_PUBLIC_API_BASE_URL ?? 'http://localhost:3000';
export default function ConversationsScreen(){const params=useLocalSearchParams<{conversationId?:string}>();const service=useMemo(()=>new MobileMessagingService(new MobileApiClient({baseUrl},new MobileSession(secureCredentialStore))),[]);const[conversationId,setConversationId]=useState(params.conversationId??'');const[messages,setMessages]=useState<MobileMessage[]>([]);const[notifications,setNotifications]=useState<MobileNotification[]>([]);const[body,setBody]=useState('');const[state,setState]=useState<'ready'|'loading'|'sending'|'error'>('ready');const[error,setError]=useState('');const reconcileNotifications=()=>service.listNotifications().then(r=>setNotifications(r.notifications)).catch(()=>{});const open=()=>{if(!conversationId.trim())return;setState('loading');setError('');service.listMessages(conversationId.trim()).then(r=>{setMessages(r.messages);setState('ready');void service.markRead(conversationId.trim());}).catch(()=>{setError('Unable to load messages');setState('error');});};useEffect(()=>{if(params.conversationId)open();},[params.conversationId]);useEffect(()=>{void reconcileNotifications();},[]);const remove=(messageId:string)=>{if(!conversationId)return;service.delete(conversationId,messageId).then(()=>setMessages(x=>x.map(m=>m.id===messageId?{...m,deletedAt:new Date().toISOString(),body:''}:m))).catch(()=>{setError('Unable to delete message');setState('error');});};const send=()=>{if(!body.trim()||!conversationId.trim())return;setState('sending');service.send(conversationId.trim(),body.trim()).then(m=>{setMessages(x=>[...x,m]);setBody('');setState('ready');}).catch(()=>{setError('Unable to send message');setState('error');});};return <SafeAreaView style={{flex:1,padding:24}}><View style={{gap:10,flex:1}}><Text accessibilityRole="header" style={{fontSize:28,fontWeight:'700'}}>Messages</Text>{!params.conversationId&&<TextInput accessibilityLabel="Conversation ID" value={conversationId} onChangeText={setConversationId} placeholder="Conversation ID"/>}<Button title="Load messages" onPress={open}/>{state==='loading'&&<ActivityIndicator accessibilityLabel="Loading messages"/>}{error&&<Text accessibilityRole="alert">{error}</Text>}<FlatList data={messages} keyExtractor={m=>m.id} renderItem={({item})=><View style={{gap:4}}><Text>{item.deletedAt?'Message deleted':item.body}</Text>{!item.deletedAt&&<Button title="Delete" onPress={()=>remove(item.id)}/>}</View>}/><TextInput accessibilityLabel="Message" value={body} onChangeText={setBody} editable={state!=='sending'}/><Button title="Send" disabled={state==='sending'} onPress={send}/></View></SafeAreaView>;}
