import { useCallback, useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, Button, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { MobileApiClient } from '../src/api-client';
import { MobileDiscoveryService, type DiscoveryItem } from '../src/discovery-service';
import { MobileSession } from '../src/session';
import { secureCredentialStore } from '../src/secure-credential-store';
const baseUrl=process.env.EXPO_PUBLIC_API_BASE_URL ?? 'http://localhost:3000';
const key=()=>globalThis.crypto?.randomUUID?.()??String(Date.now())+Math.random();
export default function DiscoverScreen(){const service=useMemo(()=>new MobileDiscoveryService(new MobileApiClient({baseUrl},new MobileSession(secureCredentialStore))),[]);const[items,setItems]=useState<DiscoveryItem[]>([]);const[index,setIndex]=useState(0);const[state,setState]=useState<'loading'|'ready'|'deciding'|'error'>('loading');const[message,setMessage]=useState('');const load=useCallback(()=>{setState('loading');setMessage('');service.discover('default').then(page=>{setItems(page.items);setIndex(0);setState('ready');}).catch(()=>{setState('error');setMessage('Unable to load discovery');});},[service]);useEffect(()=>{load();},[load]);const item=items[index];const decide=(decision:'like'|'pass')=>{if(!item)return;setState('deciding');service.decide(item.accountId,decision,key()).then(()=>{setIndex(i=>i+1);setState('ready');}).catch(()=>{setState('error');setMessage('Unable to record decision');});};if(state==='loading')return <SafeAreaView style={{flex:1,justifyContent:'center'}}><ActivityIndicator accessibilityLabel="Loading discovery"/></SafeAreaView>;if(state==='error')return <SafeAreaView style={{flex:1,padding:24,gap:12}}><Text accessibilityRole="alert">{message}</Text><Button title="Retry" onPress={load}/></SafeAreaView>;if(!item)return <SafeAreaView style={{flex:1,justifyContent:'center',padding:24}}><Text accessibilityRole="header">No more profiles</Text><Text>No additional matches are available right now.</Text><Button title="Refresh" onPress={load}/></SafeAreaView>;return <SafeAreaView style={{flex:1,padding:24}}><View style={{gap:16}}><Text accessibilityRole="header" style={{fontSize:28,fontWeight:'700'}}>Discover</Text><Text>{String(item.fields.displayName??'Profile')}</Text>{item.biography&&<Text>{item.biography}</Text>}<View style={{flexDirection:'row',gap:12}}><Button title="Pass" disabled={state==='deciding'} onPress={()=>decide('pass')}/><Button title="Like" disabled={state==='deciding'} onPress={()=>decide('like')}/></View>{state==='deciding'&&<ActivityIndicator accessibilityLabel="Saving match decision"/>}</View></SafeAreaView>;}
