import { useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, Button, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { MobileApiClient } from '../src/api-client';
import { MobileProfileService, type MobileProfile } from '../src/profile-service';
import { MobileSession } from '../src/session';
import { secureCredentialStore } from '../src/secure-credential-store';
const baseUrl=process.env.EXPO_PUBLIC_API_BASE_URL ?? 'http://localhost:3000';
export default function ProfileScreen(){const service=useMemo(()=>new MobileProfileService(new MobileApiClient({baseUrl},new MobileSession(secureCredentialStore))),[]);const[profile,setProfile]=useState<MobileProfile|null>(null);const[biography,setBiography]=useState('');const[state,setState]=useState<'loading'|'ready'|'saving'|'error'>('loading');const[message,setMessage]=useState('');const load=()=>{setState('loading');setMessage('');void service.getMine().then(p=>{setProfile(p);setBiography(p.biography??'');setState('ready');}).catch(()=>{setState('error');setMessage('Unable to load profile');});};useEffect(load,[service]);if(state==='loading')return <SafeAreaView style={{flex:1,justifyContent:'center'}}><ActivityIndicator accessibilityLabel="Loading profile"/></SafeAreaView>;if(state==='error')return <SafeAreaView style={{flex:1,padding:24,gap:12}}><Text accessibilityRole="alert">{message}</Text><Button title="Retry" onPress={load}/></SafeAreaView>;return <SafeAreaView style={{flex:1,padding:24}}><View style={{gap:12}}><Text accessibilityRole="header" style={{fontSize:28,fontWeight:'700'}}>Profile</Text><Text>Category: {profile?.categoryId}</Text><TextInput accessibilityLabel="Biography" multiline value={biography} onChangeText={setBiography} editable={state!=='saving'}/>{state==='saving'?<ActivityIndicator accessibilityLabel="Saving profile"/>:<Button title="Save profile" onPress={()=>{setState('saving');void service.updateMine({biography}).then(p=>{setProfile(p);setState('ready');}).catch(()=>{setState('error');setMessage('Unable to save profile');});}}/></View></SafeAreaView>;}
