databases:
  - name: universal-matching-platform-db
    plan: free
    region: singapore

services:
  - type: web
    name: universal-matching-platform-demo
    runtime: static
    buildCommand: pnpm install --no-frozen-lockfile && pnpm --filter @universal/web build
    staticPublishPath: apps/web/dist
    pullRequestPreviewsEnabled: true

  - type: web
    name: universal-matching-platform-api
    runtime: node
    region: singapore
    plan: free
    branch: main
    buildCommand: pnpm install --no-frozen-lockfile && pnpm --filter @universal/domain build && pnpm --filter @universal/database build && pnpm --filter @universal/api prisma:generate && pnpm --filter @universal/api build
    startCommand: pnpm --filter @universal/database migrate && pnpm --filter @universal/api start
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: universal-matching-platform-db
          property: connectionString
      - key: NODE_ENV
        value: production
      - key: HOST
        value: 0.0.0.0
      - key: CORS_ORIGINS
        value: https://universal-matching-platform-demo.onrender.com
