
import React from "react";
import { createRoot } from "react-dom/client";

const heroImage = "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=1800&q=90";
const coupleImage = "https://images.unsplash.com/photo-1511632765486-a01980e01a18?auto=format&fit=crop&w=1600&q=90";
const profileImage = "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=900&q=90";
const lifestyleImage = "https://images.unsplash.com/photo-1529333166437-7750a6dd5a70?auto=format&fit=crop&w=1200&q=90";

const features = [
  ["♡","高精度マッチング","価値観や目的、距離などを組み合わせ、あなたに合う出会いをつくります。"],
  ["◈","安心・安全","本人確認、通報、ブロックなど、安全な運営を支える機能を備えています。"],
  ["◎","多言語・多地域対応","国・地域・言語・タイムゾーンを意識したグローバル設計です。"],
  ["⌕","豊富な検索機能","年齢・地域・興味など、用途に合わせて条件を組み合わせられます。"],
  ["✦","使いやすいUI/UX","初めて触る人でも迷いにくい、シンプルで直感的な体験です。"],
  ["↯","すぐに始められる","完成済みの基盤から、自分のブランド・サービスとして展開できます。"],
];

function LandingV2() {
  return <div className="page">
    <style>{`
      *{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:#f8fafc;color:#142033;font-family:Inter,"Noto Sans JP","Hiragino Kaku Gothic ProN",Meiryo,sans-serif}button{font:inherit;cursor:pointer}.page{overflow:hidden;background:#f8fafc}.container{width:min(1220px,calc(100% - 56px));margin:auto}
      .nav{height:82px;display:flex;align-items:center;gap:32px;background:#fff}.brand{display:flex;align-items:center;gap:11px;font-size:15px;font-weight:800;letter-spacing:-.02em}.mark{width:34px;height:34px;border-radius:12px;background:#142033;color:#fff;display:grid;place-items:center;font-size:15px}.links{display:flex;gap:30px;margin-left:auto}.links a{font-size:12px;color:#667085;text-decoration:none}.navActions{display:flex;gap:9px}.login,.outline{border:1px solid #d7dde7;background:#fff;color:#253247;border-radius:12px}.login{height:42px;padding:0 19px;font-size:12px}.start,.primary{border:0;border-radius:12px;background:#142033;color:#fff;box-shadow:0 12px 28px #14203324}.start{height:42px;padding:0 20px;font-size:12px}
      .hero{padding:22px 0 28px;background:#fff}.heroInner{min-height:650px;border-radius:30px;background:#eef5f1;display:grid;grid-template-columns:48% 52%;overflow:hidden}.heroCopy{display:flex;flex-direction:column;justify-content:center;padding:70px clamp(32px,6vw,86px)}.eyebrow,.label{font-size:10px;letter-spacing:.18em;color:#7b8c83;font-weight:800}.hero h1,.title{font-family:Georgia,"Times New Roman",serif;font-weight:500;letter-spacing:-.055em}.hero h1{font-size:clamp(48px,5.2vw,76px);line-height:1.03;margin:22px 0;color:#142033}.hero h1 em,.title em{font-style:normal;color:#4d765f}.lead,.text{color:#657286;font-size:13px;line-height:1.95}.lead{max-width:510px}.buttons{display:flex;gap:10px;margin-top:28px}.primary,.outline{height:50px;padding:0 24px;font-size:12px}.heroVisual{min-height:650px;position:relative;overflow:hidden}.heroVisual:after{content:"";position:absolute;inset:0;background:linear-gradient(90deg,#eef5f100 55%,#1420331a)}.heroVisual img{width:100%;height:100%;object-fit:cover}.badge{position:absolute;z-index:2;left:28px;bottom:28px;background:#fff;padding:15px 17px;border-radius:14px;box-shadow:0 16px 40px #17283d25}.badge strong{font-size:11px;display:block}.badge span{font-size:9px;color:#7b8798}
      .trust{padding:28px 0 0;background:#fff}.trustInner{border-bottom:1px solid #e6eaf0;padding-bottom:28px;display:flex;align-items:center;justify-content:space-between;gap:20px}.trustLabel{font-size:10px;color:#8993a3;letter-spacing:.08em}.trustItems{display:flex;gap:35px;color:#657286;font-size:11px;font-weight:700}
      .featuresSection{padding:105px 0 110px;background:#fff}.featureIntro{max-width:620px}.title{font-size:clamp(40px,4.4vw,60px);line-height:1.08;margin:13px 0 17px}.featureGrid{display:grid;grid-template-columns:1.12fr .88fr;gap:70px;align-items:end}.features{display:grid;grid-template-columns:repeat(2,1fr);gap:0;margin-top:45px;border-top:1px solid #e2e7ee}.feature{padding:23px 24px 22px 0;border-bottom:1px solid #e2e7ee}.feature:nth-child(even){padding-left:24px;border-left:1px solid #e2e7ee}.icon{width:34px;height:34px;border-radius:10px;display:grid;place-items:center;background:#edf4ef;color:#466a54;font-size:15px;margin-bottom:12px}.feature h3{font-size:13px;margin:0 0 7px}.feature p{font-size:10px;line-height:1.7;color:#7b8798;margin:0}
      .showcase{background:#f1f5f3;padding:70px 0}.showcaseGrid{display:grid;grid-template-columns:44% 56%;gap:70px;align-items:center}.showcaseCopy{padding-right:20px}.showcaseVisual{min-height:520px;position:relative}.lifestyle{width:72%;height:470px;border-radius:24px;object-fit:cover;display:block;margin-left:auto}.uiPanel{position:absolute;left:0;bottom:22px;width:285px;background:#fff;border-radius:20px;padding:15px;box-shadow:0 25px 55px #182b4026}.uiTop{display:flex;justify-content:space-between;font-size:9px;color:#748095;margin-bottom:12px}.miniProfile{display:flex;align-items:center;gap:10px}.miniProfile img{width:48px;height:48px;border-radius:14px;object-fit:cover}.miniProfile strong{font-size:11px;display:block}.miniProfile span{font-size:9px;color:#8a95a5}.miniActions{display:flex;gap:6px;margin-top:14px}.miniActions span{flex:1;text-align:center;padding:9px;border-radius:10px;background:#f2f5f7;color:#5d6a7d;font-size:9px}.miniActions .active{background:#142033;color:#fff}
      .steps{background:#fff;padding:105px 0}.stepsHead{max-width:650px}.stepGrid{display:grid;grid-template-columns:repeat(3,1fr);gap:0;margin-top:55px;border-top:1px solid #e2e7ee}.step{padding:28px 30px 0 0;border-right:1px solid #e2e7ee}.step+.step{padding-left:30px}.step:last-child{border-right:0}.stepNo{font-size:11px;color:#4d765f;font-weight:800}.step h3{font-size:16px;margin:45px 0 8px}.step p{font-size:10px;line-height:1.8;color:#7b8798;margin:0;max-width:240px}
      .stats{background:#142033;color:#fff;padding:70px 0}.statsTop{display:flex;align-items:end;justify-content:space-between;gap:30px}.stats .label{color:#a9c3b1}.stats .title{color:#fff;max-width:600px}.statsGrid{display:grid;grid-template-columns:repeat(3,1fr);gap:1px;margin-top:45px;background:#3b4657}.stat{background:#142033;padding:28px}.stat strong{display:block;font:42px Georgia,serif}.stat span{font-size:10px;color:#aeb7c5}
      .useSection{padding:105px 0;background:#f8fafc}.useGrid{display:grid;grid-template-columns:repeat(3,1fr);gap:14px;margin-top:40px}.useCard{min-height:170px;padding:23px;border:1px solid #e2e7ee;border-radius:18px;background:#fff;transition:transform .2s}.useCard:hover{transform:translateY(-3px)}.useNo{font-size:9px;color:#8b97a8}.useCard h3{font:27px Georgia,serif;margin:34px 0 5px}.useCard p{font-size:10px;color:#7b8798;margin:0}.cta{background:#e8f0ea;text-align:center;padding:105px 20px}.cta .text{max-width:590px;margin:auto}.footer{background:#fff;border-top:1px solid #e5e9ef;padding:27px 0;color:#8791a1;font-size:9px}.footerInner{display:flex;justify-content:space-between;gap:20px}
      @media(max-width:1000px){.links{display:none}.heroInner{grid-template-columns:1fr}.heroVisual{min-height:470px}.featureGrid,.showcaseGrid{grid-template-columns:1fr;gap:45px}.lifestyle{width:82%}.steps{padding:75px 0}.statsTop{display:block}.useGrid{grid-template-columns:1fr 1fr}}
      @media(max-width:680px){.container{width:calc(100% - 32px)}.nav{height:70px}.navActions .login{display:none}.hero{padding:12px 0}.heroInner{border-radius:20px}.heroCopy{padding:55px 25px}.hero h1{font-size:46px}.heroVisual{min-height:390px}.trustItems{gap:12px;flex-wrap:wrap;justify-content:flex-end}.featuresSection,.steps,.useSection{padding:75px 0}.features{grid-template-columns:1fr}.feature:nth-child(even){padding-left:0;border-left:0}.showcase{padding:60px 0}.lifestyle{height:390px;width:88%}.uiPanel{width:245px}.stepGrid,.statsGrid,.useGrid{grid-template-columns:1fr}.step{border-right:0;border-bottom:1px solid #e2e7ee;padding:25px 0}.step+.step{padding-left:0}.step h3{margin:25px 0 8px}.footerInner{display:block;line-height:2.2}}
    `}</style>
    <header className="nav container">
      <div className="brand"><span className="mark">♡</span>Universal Matching</div>
      <nav className="links"><a href="#features">機能紹介</a><a href="#how">使い方</a><a href="#usecases">活用例</a><a href="#global">グローバル</a></nav>
      <div className="navActions"><button className="login">ログイン</button><button className="start">無料で始める</button></div>
    </header>

    <main>
      <section className="hero"><div className="container heroInner"><div className="heroCopy"><span className="eyebrow">A BETTER WAY TO CONNECT</span><h1>出会いを、もっと<br/><em>心地よく。</em></h1><p className="lead">人と人、人と仕事、サービスとユーザー。目的に合わせて出会い方を設計できる、次世代のマッチングプラットフォームです。</p><div className="buttons"><button className="primary">無料でデモを見る →</button><button className="outline">サービスについて</button></div></div><div className="heroVisual"><img src={heroImage} alt="人と人がつながるイメージ"/><div className="badge"><strong>WEB · iOS · Android</strong><span>地域・言語・用途に合わせて展開</span></div></div></div></section><section className="trust"><div className="container trustInner"><span className="trustLabel">ONE PLATFORM, MANY POSSIBILITIES</span><div className="trustItems"><span>恋愛</span><span>ビジネス</span><span>スキル</span><span>コミュニティ</span><span>サービス</span></div></div></section>

      <section id="features" className="featuresSection"><div className="container"><div className="featureIntro"><span className="label">WHY IT WORKS</span><h2 className="title">必要なものを、<br/><em>ひとつの体験に。</em></h2><p className="text">検索、プロフィール、マッチング、メッセージ、安全機能。利用者が迷わず使える流れを、最初からひとつにつなげています。</p></div><div className="featureGrid"><div className="features">{features.map(([icon,title,text])=><article className="feature" key={title}><div className="icon">{icon}</div><h3>{title}</h3><p>{text}</p></article>)}</div><div></div></div></div></section><section id="how" className="showcase"><div className="container showcaseGrid"><div className="showcaseCopy"><span className="label">A REAL PRODUCT EXPERIENCE</span><h2 className="title">見つける。<br/>つながる。<br/><em>続いていく。</em></h2><p className="text">プロフィールを見て、条件で探して、気になる人にLIKE。マッチしたら自然に会話へ。実際に使う流れをイメージできるUIをTOPから見せます。</p><button className="primary" style={{marginTop:24}}>デモ画面を見る →</button></div><div className="showcaseVisual"><img className="lifestyle" src={lifestyleImage} alt="利用シーン"/><div className="uiPanel"><div className="uiTop"><span>RECOMMENDED</span><span>● ONLINE</span></div><div className="miniProfile"><img src={profileImage} alt="プロフィール"/><div><strong>あなたにおすすめ</strong><span>カフェ / 旅行 / デザイン</span></div></div><div className="miniActions"><span>詳細を見る</span><span className="active">♡ LIKE</span></div></div></div></div></section><section id="global" className="stats"><div className="container"><div className="statsTop"><div><span className="label">BUILT FOR GLOBAL USE</span><h2 className="title">地域に合わせて、<br/>サービスを広げる。</h2></div><p className="text" style={{color:"#b9c2cf",maxWidth:420}}>国・地域・言語・タイムゾーンを意識した設計。ひとつの完成形ではなく、さまざまな市場に合わせて育てられます。</p></div><div className="statsGrid"><div className="stat"><strong>50+</strong><span>対応を想定する国・地域</span></div><div className="stat"><strong>3</strong><span>WEB / iOS / Android</span></div><div className="stat"><strong>∞</strong><span>用途に合わせた展開</span></div></div></div></section><section id="usecases" className="useSection"><div className="container"><span className="label">USE CASES</span><h2 className="title">出会いの目的は、<br/>ひとつじゃない。</h2><p className="text">同じ基盤から、異なる市場・サービスへ。購入者が自分のブランドとして展開しやすい汎用設計です。</p><div className="useGrid">{[["01","恋愛","価値観・距離・目的"],["02","ビジネス","採用・提携・人脈"],["03","スキル","専門家・相談・依頼"],["04","コミュニティ","地域・趣味・イベント"],["05","サービス","事業者・利用者"],["06","あなたの市場","ルールを自由に設計"]].map(([no,title,text])=><article className="useCard" key={no}><span className="useNo">{no}</span><h3>{title}</h3><p>{text}</p></article>)}</div></div></section><section className="cta"><span className="label">START YOUR SERVICE</span><h2 className="title">完成された基盤から、<br/><em>あなたのサービスを始める。</em></h2><p className="text">見た目を変えるだけでも、ソースコードから深く作り込んでも。ひとつの完成形に縛られないことが、このプラットフォームの価値です。</p><div className="buttons" style={{justifyContent:"center"}}><button className="primary">実際のデモを体験する →</button><button className="outline">詳しい仕様を見る</button></div></section>
    </main>
    <footer className="footer"><div className="container footerInner"><strong>Universal Matching Platform</strong><span>WEB · iOS · ANDROID · GLOBAL</span><span>Commercial Edition · 2026</span></div></footer>
  </div>;
}

createRoot(document.getElementById("root")!).render(<LandingV2 />);
