
import React from "react";
import { createRoot } from "react-dom/client";

const heroImage = "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=1400&q=88";
const coupleImage = "https://images.unsplash.com/photo-1516589178581-6cd7833ae3b2?auto=format&fit=crop&w=1400&q=88";
const profileImage = "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=900&q=88";

const features = [
  ["♡","高精度マッチング","価値観や目的、距離などを組み合わせ、あなたに合う出会いをつくります。"],
  ["◈","安心・安全","本人確認、通報、ブロックなど、安全な運営を支える機能を備えています。"],
  ["◎","多言語・多地域対応","国・地域・言語・タイムゾーンを意識したグローバル設計です。"],
  ["⌕","豊富な検索機能","年齢・地域・興味など、用途に合わせて条件を組み合わせられます。"],
  ["✦","使いやすいUI/UX","初めて触る人でも迷いにくい、シンプルで直感的な体験です。"],
  ["↯","すぐに始められる","完成済みの基盤から、自分のブランド・サービスとして展開できます。"],
];

function LandingV2() {
  return <div className="page">
    <style>{`
      *{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:#fff;color:#172238;font-family:Inter,"Noto Sans JP","Hiragino Kaku Gothic ProN",Meiryo,sans-serif}button{font:inherit;cursor:pointer}.page{overflow:hidden;background:#fff}.container{width:min(1180px,calc(100% - 64px));margin:auto}
      .nav{height:78px;display:flex;align-items:center;gap:28px;background:#fff}.brand{display:flex;align-items:center;gap:10px;font-size:17px;font-weight:700;white-space:nowrap}.mark{width:30px;height:30px;border:2px solid #5c8cff;border-radius:10px 14px 10px 14px;display:grid;place-items:center;color:#4e82f1}.links{display:flex;gap:32px;margin-left:auto}.links a{font-size:12px;color:#697586;text-decoration:none}.navActions{display:flex;gap:9px}.login,.outline{border:1px solid #c5ccd7;background:#fff;color:#344054;border-radius:25px}.login{height:42px;padding:0 21px;font-size:12px}.start,.primary{border:0;border-radius:25px;background:linear-gradient(135deg,#4ea7ff,#6259f4);color:#fff;box-shadow:0 10px 24px #567bf333}.start{height:42px;padding:0 23px;font-size:12px}
      .hero{display:grid;grid-template-columns:44% 56%;min-height:590px;background:linear-gradient(105deg,#f4fbff,#fff 50%,#eaf7ff)}.heroCopy{display:flex;flex-direction:column;justify-content:center;padding:65px max(30px,calc((100vw - 1180px)/2)) 65px}.eyebrow,.label{font-size:10px;letter-spacing:.17em;color:#548de9;font-weight:700}.hero h1,.title{font-family:Georgia,"Times New Roman",serif;font-weight:500;letter-spacing:-.05em}.hero h1{font-size:clamp(43px,5vw,70px);line-height:1.12;margin:20px 0;color:#172238}.hero h1 em,.title em{font-style:normal;color:#4d7ff0}.lead,.text{color:#657286;font-size:13px;line-height:1.95}.lead{max-width:530px}.buttons{display:flex;gap:11px;margin-top:25px}.primary,.outline{height:48px;padding:0 27px;font-size:12px}.storeRow{display:flex;gap:7px;margin-top:15px}.store{background:#111;color:#fff;border-radius:6px;padding:8px 12px;font-size:9px}.heroVisual{min-height:590px;position:relative;overflow:hidden}.heroVisual img{width:100%;height:100%;object-fit:cover}.badge{position:absolute;left:38px;bottom:30px;background:#ffffffdf;backdrop-filter:blur(12px);padding:14px 17px;border-radius:15px;box-shadow:0 12px 32px #21334d22}.badge strong{font-size:11px;display:block}.badge span{font-size:9px;color:#758196}
      .featuresSection{padding:85px 0 95px}.featureGrid{display:grid;grid-template-columns:47% 53%;gap:50px;align-items:center}.title{font-size:clamp(37px,4vw,54px);line-height:1.15;margin:12px 0 16px}.features{display:grid;grid-template-columns:repeat(3,1fr);gap:26px 18px;margin-top:35px}.icon{width:42px;height:42px;border-radius:50%;display:grid;place-items:center;background:#edf4ff;color:#5c82ef;font-size:20px;margin-bottom:12px}.feature h3{font-size:13px;margin:0 0 7px}.feature p{font-size:10px;line-height:1.7;color:#7b8798;margin:0}
      .phones{min-height:500px;position:relative;display:flex;align-items:center;justify-content:center}.phone{width:242px;height:480px;border:7px solid #121a27;border-radius:36px;overflow:hidden;background:#fff;box-shadow:0 25px 55px #1d2c431f}.phone.back{position:absolute;transform:translate(105px,18px) scale(.91);z-index:1}.phone.front{transform:translate(-32px,-2px);z-index:2}.phoneTop{height:30px;text-align:center;padding-top:7px;font-size:8px;color:#667085}.profilePhoto{height:252px}.profilePhoto img{width:100%;height:100%;object-fit:cover}.profileInfo{padding:14px}.name{font:24px Georgia,serif}.meta{font-size:9px;color:#7b8799;margin-top:3px}.chips{display:flex;gap:5px;margin-top:10px}.chip{background:#eef4ff;color:#5272b4;border-radius:12px;padding:5px 7px;font-size:8px}.rounds{display:flex;justify-content:center;gap:12px;padding:9px}.round{width:38px;height:38px;border:0;border-radius:50%;background:#eef4ff;color:#5277ee}.like{background:linear-gradient(135deg,#ff89ae,#ff5e87);color:#fff}.chat{padding:13px;background:#f7f9fc;height:420px}.chat h4{margin:0 0 13px;font-size:12px}.bubble{font-size:9px;line-height:1.5;padding:9px 11px;border-radius:14px;background:#fff;color:#56657a;max-width:82%;margin:7px 0}.right{margin-left:auto;background:#6688ef;color:#fff}
      .steps{display:grid;grid-template-columns:50% 50%;min-height:430px;background:#fafcff}.stepsCopy{padding:75px max(30px,calc((100vw - 1180px)/2)) 70px}.stepGrid{display:grid;grid-template-columns:repeat(3,1fr);gap:14px;margin-top:40px}.stepNo{width:29px;height:29px;border-radius:50%;background:#e7f0ff;color:#4e8af1;display:grid;place-items:center;font-size:11px;font-weight:700}.step h3{font-size:12px;margin:10px 0 6px}.step p{font-size:9px;line-height:1.7;color:#7b8798;margin:0}.stepPhoto{min-height:430px;position:relative;overflow:hidden}.stepPhoto img{width:100%;height:100%;object-fit:cover}.caption{position:absolute;right:35px;bottom:27px;color:#fff;font:27px cursive;text-shadow:0 2px 12px #0005}
      .stats{position:relative;min-height:275px;overflow:hidden;color:#fff;text-align:center}.stats img{position:absolute;width:100%;height:100%;object-fit:cover;opacity:.34}.overlay{position:absolute;inset:0;background:linear-gradient(#17334faa,#18334ddd)}.statsContent{position:relative;padding:55px 0 58px}.statsLabel{font-size:10px;letter-spacing:.1em}.statsGrid{display:flex;justify-content:center;gap:75px;margin:24px 0}.stat strong{display:block;font-size:30px;font-weight:500}.stat span{font-size:9px;color:#c9d4e1}.stats .primary{margin:0}
      .useSection{padding:82px 0}.useGrid{display:grid;grid-template-columns:repeat(3,1fr);gap:15px;margin-top:34px}.useCard{min-height:135px;padding:22px;border:1px solid #e6ebf2;border-radius:17px;background:linear-gradient(145deg,#fff,#f8fbff);box-shadow:0 8px 28px #283e5e0b}.useNo{font-size:9px;color:#7ca1e8}.useCard h3{font:24px Georgia,serif;margin:25px 0 4px}.useCard p{font-size:10px;color:#7b8798;margin:0}.cta{text-align:center;padding:95px 20px;background:linear-gradient(135deg,#f3f9ff,#fff,#f5f2ff)}.cta .text{max-width:560px;margin:auto}.footer{border-top:1px solid #e8ebf0;padding:27px 0;color:#8791a1;font-size:9px}.footerInner{display:flex;justify-content:space-between;gap:20px}
      @media(max-width:1000px){.links{display:none}.hero{grid-template-columns:1fr}.heroVisual{min-height:470px}.featureGrid{grid-template-columns:1fr}.steps{grid-template-columns:1fr}.stepsCopy{padding:65px 32px}.stepPhoto{min-height:360px}.useGrid{grid-template-columns:1fr 1fr}}
      @media(max-width:680px){.container{width:calc(100% - 32px)}.brand{font-size:14px}.navActions .login{display:none}.heroCopy{padding:55px 24px}.hero h1{font-size:43px}.features{grid-template-columns:1fr 1fr}.phone{width:205px;height:430px}.profilePhoto{height:215px}.phone.front{transform:translate(-25px,-2px)}.phone.back{transform:translate(82px,18px) scale(.9)}.statsGrid{gap:25px}.useGrid{grid-template-columns:1fr}.footerInner{display:block;line-height:2}.stepGrid{grid-template-columns:1fr;gap:20px}}
      @media(max-width:430px){.features{grid-template-columns:1fr}.heroButtons{flex-direction:column}.phones{transform:scale(.88);margin:-20px 0}.statsGrid{gap:15px}.stat strong{font-size:22px}}
    `}</style>
    <header className="nav container">
      <div className="brand"><span className="mark">♡</span>Universal Matching</div>
      <nav className="links"><a href="#features">機能紹介</a><a href="#how">使い方</a><a href="#usecases">活用例</a><a href="#global">グローバル</a></nav>
      <div className="navActions"><button className="login">ログイン</button><button className="start">無料で始める</button></div>
    </header>

    <main>
      <section className="hero">
        <div className="heroCopy"><span className="eyebrow">YOUR NEXT CONNECTION</span><h1>つながる、広がる、<br/>新しい<em>出会いのカタチ</em></h1><p className="lead">同じ価値観、同じ興味、同じ未来を描ける人と出会える。恋愛だけに限らない、次世代のマッチングプラットフォームです。</p><div className="buttons"><button className="primary">今すぐ無料で始める →</button><button className="outline">アプリをダウンロード</button></div><div className="storeRow"><span className="store">● App Store</span><span className="store">▶ Google Play</span></div></div>
        <div className="heroVisual"><img src={heroImage} alt="マッチングサービスのイメージ"/><div className="badge"><strong>あなたに合う出会いを、もっと自然に。</strong><span>WEB · iOS · Android · Global</span></div></div>
      </section>

      <section id="features" className="featuresSection"><div className="container featureGrid"><div><span className="label">FEATURES</span><h2 className="title">選ばれる6つの理由</h2><p className="text">ただ人をつなぐだけではなく、検索・プロフィール・メッセージ・安全機能までをひとつの体験にまとめています。</p><div className="features">{features.map(([icon,title,text])=><article className="feature" key={title}><div className="icon">{icon}</div><h3>{title}</h3><p>{text}</p></article>)}</div></div>
        <div className="phones"><div className="phone back"><div className="phoneTop">9:41　Universal Matching</div><div className="chat"><h4>あやか</h4><div className="bubble">はじめまして！マッチありがとうございます😊</div><div className="bubble right">こちらこそ！よろしくお願いします！</div><div className="bubble">週末、カフェ巡りしませんか？</div><div className="bubble right">ぜひ行きましょう☕</div></div></div><div className="phone front"><div className="phoneTop">9:41　Universal Matching</div><div className="profilePhoto"><img src={profileImage} alt="プロフィール"/></div><div className="profileInfo"><div className="name">あやか <small style={{fontFamily:"Inter",fontSize:11}}>26</small></div><div className="meta">カフェ巡り / 旅行 / デザイン</div><div className="chips"><span className="chip">カフェ</span><span className="chip">旅行</span><span className="chip">写真</span></div></div><div className="rounds"><button className="round">×</button><button className="round like">♥</button><button className="round">★</button></div></div></div>
      </div></section>

      <section id="how" className="steps"><div className="stepsCopy"><span className="label">HOW IT WORKS</span><h2 className="title">かんたん3ステップで始められる</h2><p className="text">登録からマッチングまで、たったの3ステップ。シンプルだから、初めての人でも迷いません。</p><div className="stepGrid"><div className="step"><div className="stepNo">1</div><h3>会員登録</h3><p>メールアドレスやSNSで簡単に登録できます。</p></div><div className="step"><div className="stepNo">2</div><h3>プロフィール作成</h3><p>あなたのことを知ってもらうためにプロフィールを作成。</p></div><div className="step"><div className="stepNo">3</div><h3>マッチング開始</h3><p>理想の相手を見つけて、メッセージを送りましょう。</p></div></div></div><div className="stepPhoto"><img src={coupleImage} alt="新しい出会いのイメージ"/><div className="caption">New encounters,<br/>new stories.</div></div></section>

      <section id="global" className="stats"><img src={heroImage} alt=""/><div className="overlay"></div><div className="statsContent container"><div className="statsLabel">今、世界中で選ばれています</div><div className="statsGrid"><div className="stat"><strong>100万人+</strong><span>累計登録者数</span></div><div className="stat"><strong>50か国+</strong><span>対応国・地域</span></div><div className="stat"><strong>98%</strong><span>マッチング成功率</span></div></div><button className="primary">今すぐ無料で始める →</button></div></section>

      <section id="usecases" className="useSection"><div className="container"><span className="label">USE CASES</span><h2 className="title">出会いの目的は、ひとつじゃない。</h2><p className="text">恋愛、ビジネス、スキル、地域、コミュニティ。購入者が自分のサービスとして展開できる、汎用的なマッチング体験を想定しています。</p><div className="useGrid">{[["01","恋愛","価値観・距離・目的"],["02","ビジネス","採用・提携・人脈"],["03","スキル","専門家・相談・依頼"],["04","コミュニティ","地域・趣味・イベント"],["05","サービス","事業者・利用者"],["06","あなたの市場","ルールを自由に設計"]].map(([no,title,text])=><article className="useCard" key={no}><span className="useNo">{no}</span><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>

      <section className="cta"><span className="label">START YOUR SERVICE</span><h2 className="title">完成された基盤から、<br/><em>あなたのサービスを始める。</em></h2><p className="text">見た目を変えるだけでも、ソースコードから深く作り込んでも。ひとつの完成形に縛られないことが、このプラットフォームの価値です。</p><div className="buttons" style={{justifyContent:"center"}}><button className="primary">実際のデモを体験する →</button><button className="outline">詳しい仕様を見る</button></div></section>
    </main>
    <footer className="footer"><div className="container footerInner"><strong>Universal Matching Platform</strong><span>WEB · iOS · ANDROID · GLOBAL</span><span>Commercial Edition · 2026</span></div></footer>
  </div>;
}

createRoot(document.getElementById("root")!).render(<LandingV2 />);
