import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { getAuthenticatedAccount, register, signIn, verifyEmail, createConversation, listMessages, sendMessage, API_BASE_URL, listProfileCategories, createMyProfile, discoverProfiles, decideMatch, createConversationFromMutualMatch, listNotifications, markNotificationRead, getMyProfile, updateMyProfile, type Account, type Message, type RealtimeEvent, type ProfileCategory, type DiscoveryProfile } from './api';
import './styles.css';
import { Button, Card, Field, List, ListRow, StatusMessage, TextArea, TextInput } from './components/AccessiblePrimitives';
import { HeaderNavigation } from './components/NavigationPrimitives';
import { DiscoveryPresentation, type DiscoveryPresentationMode } from './components/DiscoveryPresentation';

type Feature = { icon: string; title: string; text: string };
type Screen = 'home' | 'signin' | 'register' | 'verify' | 'dashboard';
type AccessStatus = 'idle' | 'loading' | 'success' | 'error';
type NotificationItem = { id: string; kind: string; createdAt: string; readAt?: string | null };

const features: Feature[] = [
  { icon: '✦', title: 'Meaningful connections', text: 'A thoughtful space designed around real conversations.' },
  { icon: '◌', title: 'Privacy first', text: 'Your experience is built with clear boundaries and control.' },
  { icon: '↗', title: 'Global by design', text: 'A flexible foundation ready for communities across markets.' },
];

function AccessForm({ screen, onBack, onSignedIn }: { screen: 'signin' | 'register'; onBack: () => void; onSignedIn: () => void }) {
  const [email, setEmail] = useState(''); const [password, setPassword] = useState('');
  const [status, setStatus] = useState<AccessStatus>('idle'); const [message, setMessage] = useState('');
  async function submit(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault(); setStatus('loading'); setMessage('');
    try { if (screen === 'signin') { const body = await signIn(email, password); if (!body.credential) throw new Error('Invalid email or password'); sessionStorage.setItem('connect.credential', body.credential); setStatus('success'); setMessage('Signed in successfully. Loading your account…'); onSignedIn(); } else { await register(email, password); setStatus('success'); setMessage('Registration received. Please check your email for the verification step.'); } }
    catch (error) { setStatus('error'); setMessage(error instanceof Error ? error.message : 'Something went wrong. Please try again.'); }
  }
  const title = screen === 'signin' ? 'Welcome back.' : 'Start your journey.';
  const tone = status === 'error' ? 'error' : 'success';
  return <main className="accessPage"><nav aria-label="Access navigation"><Button className="brand plain" onClick={onBack}><span className="brandMark">C</span>connect</Button><Button className="textButton" onClick={onBack}>← Back</Button></nav>
    <section className="accessCard" aria-labelledby="access-title"><div className="eyebrow">{screen === 'signin' ? 'WELCOME BACK' : 'CREATE YOUR ACCOUNT'}</div><h1 id="access-title">{title}</h1><p>{screen === 'signin' ? 'Sign in to continue your conversations and connections.' : 'Create your account and discover a more thoughtful way to connect.'}</p>
      <form onSubmit={submit}>
        <Field label="Email" id="access-email" required><TextInput value={email} onChange={(e) => setEmail(e.target.value)} type="email" placeholder="you@example.com" required autoComplete="email" /></Field>
        <Field label="Password" id="access-password" required><TextInput value={password} onChange={(e) => setPassword(e.target.value)} type="password" placeholder="At least 8 characters" minLength={8} required autoComplete={screen === 'signin' ? 'current-password' : 'new-password'} /></Field>
        {screen === 'register' && <label className="check"><input type="checkbox" required /> <span>I agree to the Terms and Privacy Policy.</span></label>}
        <Button className="primary wide" type="submit" loading={status === 'loading'} loadingLabel="Please wait…">{screen === 'signin' ? 'Sign in →' : 'Create account →'}</Button>
        {status !== 'idle' && <StatusMessage tone={tone}>{message}</StatusMessage>}
        {screen === 'register' && status === 'success' && <a className="textButton verifyLink" href="#verify">Already have a token? Verify email →</a>}
      </form></section></main>;
}

function VerifyEmail({ onBack }: { onBack: () => void }) {
 const [token,setToken]=useState(''); const [status,setStatus]=useState<AccessStatus>('idle'); const [message,setMessage]=useState('');
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setStatus('loading');setMessage('');try{const body=await verifyEmail(token);if(!body.verified)throw new Error('This verification link is invalid or has expired.');setStatus('success');setMessage('Email verified successfully. You can now sign in.');}catch(error){setStatus('error');setMessage(error instanceof Error?error.message:'Verification failed.');}}
 return <main className="accessPage"><nav aria-label="Verification navigation"><Button className="brand plain" onClick={onBack}><span className="brandMark">C</span>connect</Button><Button className="textButton" onClick={onBack}>← Back</Button></nav><section className="accessCard" aria-labelledby="verify-title"><div className="eyebrow">VERIFY YOUR EMAIL</div><h1 id="verify-title">One last step.</h1><p>Paste the verification token from your email to activate your account.</p><form onSubmit={submit}><Field label="Verification token" id="verification-token" required><TextInput value={token} onChange={(e)=>setToken(e.target.value)} placeholder="Paste your secure token" required autoComplete="one-time-code" /></Field><Button className="primary wide" loading={status==='loading'} loadingLabel="Verifying…" type="submit">Verify email →</Button>{status!=='idle'&&<StatusMessage tone={status==='error'?'error':'success'}>{message}</StatusMessage>}</form></section></main>;
}

function Dashboard({ account, loading, error, onSignOut }: { account: Account | null; loading: boolean; error: string; onSignOut: () => void }) {
 const [conversationId,setConversationId]=useState(''); const [participantId,setParticipantId]=useState(''); const [messages,setMessages]=useState<Message[]>([]); const [body,setBody]=useState(''); const [messageStatus,setMessageStatus]=useState(''); const [realtimeStatus,setRealtimeStatus]=useState('offline');
 useEffect(()=>{const credential=sessionStorage.getItem('connect.credential');if(!credential)return;const controller=new AbortController();setRealtimeStatus('connecting');void fetch(API_BASE_URL+'/realtime/events',{headers:{authorization:'Bearer '+credential},signal:controller.signal}).then(async response=>{if(!response.ok)throw new Error('Realtime connection unavailable');setRealtimeStatus('connected');const reader=response.body?.getReader();if(!reader)return;const decoder=new TextDecoder();let buffer='';while(!controller.signal.aborted){const chunk=await reader.read();if(chunk.done)break;buffer+=decoder.decode(chunk.value,{stream:true});const blocks=buffer.split('\n\n');buffer=blocks.pop()??'';for(const block of blocks){const dataLine=block.split('\n').find(line=>line.startsWith('data:'));if(!dataLine)continue;try{const event=JSON.parse(dataLine.slice(5).trim()) as RealtimeEvent;if(event.eventType==='message.created'&&event.payload.conversationId===conversationId){void listMessages(conversationId).then(result=>setMessages(result.messages.slice().reverse())).catch(()=>{});setMessageStatus('New message received.');}}catch{}}}}).catch(()=>setRealtimeStatus('offline'));return()=>controller.abort();},[conversationId]);
 async function openConversation(e:React.FormEvent){e.preventDefault();setMessageStatus('');try{const created=await createConversation([participantId]);setConversationId(created.id);const result=await listMessages(created.id);setMessages(result.messages.slice().reverse());setMessageStatus('Conversation ready.');}catch(err){setMessageStatus(err instanceof Error?err.message:'Unable to create conversation.');}}
 async function submitMessage(e:React.FormEvent){e.preventDefault();if(!conversationId)return;try{const sent=await sendMessage(conversationId,body);setMessages(items=>[...items,sent]);setBody('');}catch(err){setMessageStatus(err instanceof Error?err.message:'Message failed.');}}
 return <main className="dashboard">
 <HeaderNavigation ariaLabel="Dashboard navigation" brand={<div className="brand"><span className="brandMark">C</span>connect</div>} items={[{ href: '#dashboard', label: 'Dashboard', active: true }, { href: '#discovery', label: 'Discover' }, { href: '#notifications', label: 'Activity' }, { href: '#conversations', label: 'Conversations' }]} />
 <div className="dashboardActions"><Button className="ghost" onClick={onSignOut}>Sign out</Button></div>
 <section id="dashboard" className="dashboardHero" aria-labelledby="dashboard-title"><div><div className="eyebrow">YOUR SPACE</div><h1 id="dashboard-title">Welcome to<br/><em>Connect.</em></h1><p>Your account is securely connected to the platform.</p></div><div className="accountPanel" aria-live="polite">{loading?<><span className="panelLabel">ACCOUNT</span><p>Loading your account…</p></>:error?<><h2>We couldn't load your account.</h2><StatusMessage tone="error">{error}</StatusMessage></>:account?<><span className="panelLabel">ACCOUNT STATUS</span><strong>{account.status}</strong><span className="panelLabel">MEMBER SINCE</span><p>{new Date(account.createdAt).toLocaleDateString()}</p><span className="panelLabel">ACCOUNT ID</span><code>{account.id}</code></>:null}</div></section>
 <div id="notifications"><NotificationInbox /></div>
 <div id="discovery"><Discovery onMessageTarget={(id)=>{setParticipantId(id);window.scrollTo({top:document.body.scrollHeight,behavior:'smooth'});}} /></div>
 <section id="conversations" className="messagesSection" aria-labelledby="conversations-title"><div><span className="eyebrow">CONVERSATIONS</span><h2 id="conversations-title">Start a real conversation.</h2><p>Create a conversation with an existing account ID. This UI uses only the currently exposed backend contract.</p><Card className="conversationComposer"><form className="conversationForm" onSubmit={openConversation}><Field label="Participant account ID" id="participant-account-id" description="Open a conversation using an account ID authorized by the backend."><TextInput value={participantId} onChange={e=>setParticipantId(e.target.value)} placeholder="Participant account ID" required/></Field><Button className="primary" type="submit">Open conversation →</Button></form>{messageStatus&&<StatusMessage tone={messageStatus.includes("Unable")||messageStatus.includes("failed")?"error":"success"}>{messageStatus}</StatusMessage>}</Card></div>
 {conversationId&&<Card className="chatPanel" aria-live="polite"><div className="chatHeader"><span>SECURE CONVERSATION · REALTIME {realtimeStatus}</span><code>{conversationId}</code></div><List className="messageList" aria-label="Conversation messages">{messages.length?messages.map(m=><ListRow key={m.id} className="message"><p>{m.body}</p><small>{new Date(m.createdAt).toLocaleString()}</small></ListRow>):<li className="empty">No messages yet. Start the conversation.</li>}</List><form className="sendForm" onSubmit={submitMessage}><Field label="Message" id="conversation-message"><TextArea value={body} onChange={e=>setBody(e.target.value)} placeholder="Write a message…" required rows={3}/></Field><Button className="primary" type="submit">Send →</Button></form></Card>}</section></main>;
}
function NotificationInbox(){
 const [items,setItems]=useState<NotificationItem[]>([]);const [status,setStatus]=useState('');const [loading,setLoading]=useState(true);
 const load=async()=>{setLoading(true);try{const r=await listNotifications();setItems(r.notifications);setStatus('');}catch(e){setStatus(e instanceof Error?e.message:'Notifications unavailable.');}finally{setLoading(false);}};
 useEffect(()=>{void load();const interval=window.setInterval(()=>void load(),30000);const refresh=()=>void load();window.addEventListener('focus',refresh);return()=>{window.clearInterval(interval);window.removeEventListener('focus',refresh);};},[]);
 async function read(id:string){try{const r=await markNotificationRead(id);if(r.updated)setItems(xs=>xs.map(x=>x.id===id?{...x,readAt:new Date().toISOString()}:x));}catch(e){setStatus(e instanceof Error?e.message:'Unable to mark notification read.');}}
 return <section className="notificationSection" aria-labelledby="notification-title"><div><span className="eyebrow">ACTIVITY</span><h2 id="notification-title">Stay in the loop.</h2><p>Important activity from your account, securely scoped to you.</p></div><Card className="notificationList" aria-live="polite">{status&&<StatusMessage tone="error">{status}</StatusMessage>}{loading?<p className="emptyActivity" role="status">Loading activity…</p>:items.length===0?<p className="emptyActivity">You're all caught up.</p>:<List aria-label="Account activity">{items.map(item=><ListRow key={item.id} interactive={!item.readAt} disabled={Boolean(item.readAt)} onActivate={()=>!item.readAt&&void read(item.id)} activateLabel={!item.readAt?`Mark ${item.kind.replaceAll('.',' ')} notification as read`:undefined} className={'notificationItem '+(item.readAt?'isRead':'')}><span className="notificationDot" aria-hidden="true"/><span><strong>{item.kind.replaceAll('.',' ')}</strong><small>{new Date(item.createdAt).toLocaleString()}</small></span>{!item.readAt&&<em>NEW</em>}</ListRow>)}</List>}</Card></section>;
}

function Discovery({ onMessageTarget }: { onMessageTarget: (id:string)=>void }) {
 const [presentation,setPresentation]=useState<DiscoveryPresentationMode>('grid');const [categories,setCategories]=useState<ProfileCategory[]>([]);const [categoryId,setCategoryId]=useState('');const [fields,setFields]=useState<Record<string, string | number | boolean | null>>({});const [ready,setReady]=useState(false);const [profiles,setProfiles]=useState<DiscoveryProfile[]>([]);const [nextCursor,setNextCursor]=useState<string|undefined>();const [discovering,setDiscovering]=useState(false);const [status,setStatus]=useState('');
 useEffect(()=>{void Promise.all([listProfileCategories(),getMyProfile()]).then(([cats,profile])=>{setCategories(cats.categories);if(profile){setCategoryId(profile.categoryId);setFields(profile.fields);setReady(true);}else if(cats.categories[0])setCategoryId(cats.categories[0].id);}).catch(e=>setStatus(e instanceof Error?e.message:'Discovery setup unavailable.'));},[]);
 async function saveProfile(e:React.FormEvent){e.preventDefault();try{const payload={categoryId,fields,geographicScope:{kind:'global'}};if(ready)await updateMyProfile(payload);else await createMyProfile(payload);setReady(true);setStatus('Profile saved. Discover people.');}catch(e){setStatus(e instanceof Error?e.message:'Unable to save profile.');}}
 async function discover(more=false){setDiscovering(true);try{const r=await discoverProfiles({categoryId,limit:20,cursor:more?nextCursor:undefined});setProfiles(current=>{const source=more?[...current,...r.items]:r.items;const seen=new Set<string>();const merged=source.filter(item=>!seen.has(item.accountId)&&Boolean(seen.add(item.accountId)));setStatus(merged.length?'Choose who you want to connect with.':'No profiles available yet.');return merged;});setNextCursor(r.nextCursor);}catch(e){setStatus(e instanceof Error?e.message:'Discovery unavailable.');}finally{setDiscovering(false);}}
 async function decision(targetAccountId:string,decision:'like'|'pass'){try{const r=await decideMatch({targetAccountId,decision,idempotencyKey:crypto.randomUUID()});setProfiles(items=>items.filter(p=>p.accountId!==targetAccountId));setStatus(r.mutual?'It’s a match — you can start a conversation.':decision==='like'?'Interest sent.':'Passed.');if(r.mutual){const conversation=await createConversationFromMutualMatch(targetAccountId);onMessageTarget(targetAccountId);setStatus('It’s a match — secure conversation authorized: '+conversation.id);}}catch(e){setStatus(e instanceof Error?e.message:'Unable to update connection.');}}
 const schema=categories.find(x=>x.id===categoryId)?.fieldSchema??{};
 return <section className="discoverySection" aria-labelledby="discovery-title"><div className="discoveryIntro"><span className="eyebrow">DISCOVER</span><h2 id="discovery-title">Meet the right people.</h2><p>Build your public profile, then explore people through the platform's server-authorized discovery system.</p>{status&&<StatusMessage tone={status.includes('Unable')||status.includes('unavailable')?'error':'success'}>{status}</StatusMessage>}</div>
 <Card className="profileCard"><form className="profileForm" onSubmit={saveProfile}><Field label="Category" id="profile-category" required><select value={categoryId} onChange={e=>{setCategoryId(e.target.value);setProfiles([]);setNextCursor(undefined);setStatus('');}} required>{categories.map(x=><option key={x.id} value={x.id}>{x.displayName??x.key??x.id}</option>)}</select></Field>{Object.entries(schema).map(([key,rule])=>{const config=rule as {kind?:string;required?:boolean};const label=key.replace(/([A-Z])/g,' $1').replace(/^./,x=>x.toUpperCase());return <Field key={key} label={label} id={'profile-'+key} required={config.required}>{config.kind==='boolean'?<input type="checkbox" checked={Boolean(fields[key])} onChange={e=>setFields({...fields,[key]:e.target.checked})}/>:config.kind==='number'?<TextInput type="number" required={config.required} value={String(fields[key]??'')} onChange={e=>setFields({...fields,[key]:e.target.value===''?null:Number(e.target.value)})}/>:key==='bio'?<TextArea required={config.required} value={String(fields[key]??'')} onChange={e=>setFields({...fields,[key]:e.target.value})}/>:<TextInput required={config.required} value={String(fields[key]??'')} onChange={e=>setFields({...fields,[key]:e.target.value})}/>}</Field>;})}<Button className="primary">{ready?'Update profile →':'Save profile →'}</Button></form></Card>
 {ready&&<div className="discoveryResults"><Button className="primary" onClick={()=>void discover()} loading={discovering} loadingLabel="Loading…">Discover people →</Button><div className="presentationControls" role="group" aria-label="Discovery presentation"><Button className={presentation==='card'?'primary':'pass'} onClick={()=>setPresentation('card')}>Cards</Button><Button className={presentation==='list'?'primary':'pass'} onClick={()=>setPresentation('list')}>List</Button><Button className={presentation==='grid'?'primary':'pass'} onClick={()=>setPresentation('grid')}>Grid</Button></div><DiscoveryPresentation mode={presentation}>{profiles.map(p=>{const profileFields=p.fields as Record<string, unknown>;return <Card className="profileCard" key={p.accountId}><div className="avatar" aria-hidden="true">{String(profileFields.displayName??'?').slice(0,1)}</div><h3>{String(profileFields.displayName??'Member')}</h3><p className="headline">{String(profileFields.headline??'')}</p><p>{String(profileFields.bio??'')}</p><div className="decisionRow"><Button className="pass" onClick={()=>void decision(p.accountId,'pass')}>Pass</Button><Button className="primary" onClick={()=>void decision(p.accountId,'like')}>Connect →</Button></div></Card>})}</DiscoveryPresentation>{nextCursor&&<Button className="pass loadMore" loading={discovering} loadingLabel="Loading…" onClick={()=>void discover(true)}>Load more people</Button>}</div>}</section>;
}

function Home({ setScreen }: { setScreen: (screen: Screen) => void }) { return <main><nav aria-label="Main navigation"><div className="brand"><span className="brandMark">C</span>connect</div><div className="navLinks"><a href="#experience">Experience</a><a href="#safety">Safety</a><Button className="ghost" onClick={() => setScreen('signin')}>Sign in</Button></div></nav><section className="hero"><div className="eyebrow">HUMAN CONNECTION, REIMAGINED</div><h1>Meet beyond<br/><em>the ordinary.</em></h1><p>A modern space for discovering people, starting conversations, and building meaningful connections.</p><div className="actions"><Button className="primary" onClick={() => setScreen('register')}>Start exploring <span>→</span></Button><a className="textButton" href="#experience">How it works</a></div><div className="proof"><div><strong>Private</strong><span>Designed for control</span></div><div><strong>Global</strong><span>Built without borders</span></div><div><strong>Thoughtful</strong><span>Human at the center</span></div></div></section><section id="experience" className="featureSection"><div className="sectionIntro"><span>01 / THE EXPERIENCE</span><h2>Less noise.<br/>More <em>possibility.</em></h2></div><div className="featureGrid">{features.map(feature=><article key={feature.title}><div className="featureIcon">{feature.icon}</div><h3>{feature.title}</h3><p>{feature.text}</p><a href="#start">Discover more →</a></article>)}</div></section><section id="safety" className="statement"><span>BUILT FOR THE REAL WORLD</span><h2>Connection feels better<br/>when trust comes first.</h2><p>Clear controls, thoughtful interactions, and a platform architecture designed to grow responsibly.</p></section><footer id="start"><div className="brand"><span className="brandMark">C</span>connect</div><p>© 2026 Connect. A universal platform foundation.</p><Button className="primary" onClick={() => setScreen('register')}>Get started →</Button></footer></main>; }

function App(){const [screen,setScreen]=useState<Screen>(()=>window.location.hash==='#verify'?'verify':sessionStorage.getItem('connect.credential')?'dashboard':'home');const [account,setAccount]=useState<Account|null>(null);const [loading,setLoading]=useState(false);const [error,setError]=useState('');
 useEffect(()=>{const sync=()=>setScreen(window.location.hash==='#verify'?'verify':'home');window.addEventListener('hashchange',sync);return()=>window.removeEventListener('hashchange',sync);},[]);
 useEffect(()=>{if(screen!=='dashboard')return;setLoading(true);setError('');getAuthenticatedAccount().then(setAccount).catch(e=>{setError(e instanceof Error?e.message:'Account lookup failed');sessionStorage.removeItem('connect.credential');}).finally(()=>setLoading(false));},[screen]);
 const signOut=()=>{sessionStorage.removeItem('connect.credential');setAccount(null);setScreen('home');};
 if(screen==='home')return <Home setScreen={setScreen}/>;if(screen==='verify')return <VerifyEmail onBack={()=>setScreen('home')}/>;if(screen==='dashboard')return <Dashboard account={account} loading={loading} error={error} onSignOut={signOut}/>;return <AccessForm screen={screen} onBack={()=>setScreen('home')} onSignedIn={()=>setScreen('dashboard')}/>;}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
